server:
  port: 8081
  tomcat:
    relaxed-query-chars:
      - '['
      - ']'
      - '{'
      - '}'
  servlet:
    context-path: /mds

spring:
  datasource:
    datasource1:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/course_db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      type: com.alibaba.druid.pool.DruidDataSource
    datasource2:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/course_db1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml   #映射文件路径
  configuration:
    map-underscore-to-camel-case: true      #开启驼峰命名
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl









